<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert(array (
            0 => 
            array (
                'name' => '*',
                'description' => 'All permissions',
                'slug' => '*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            1 => 
            array (
                'name' => 'admin.*',
                'description' => 'All admin permissions',
                'slug' => 'admin.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            2 => 
            array (
                'name' => 'admin.panel.*',
                'description' => 'All admin panel permissions',
                'slug' => 'admin.panel.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            3 => 
            array (
                'name' => 'admin.panel.view',
                'description' => 'View admin panel',
                'slug' => 'admin.panel.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            4 => 
            array (
                'name' => 'authorization.type.*',
                'description' => 'All authorization type permissions',
                'slug' => 'authorization.type.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            5 => 
            array (
                'name' => 'authorization.type.view',
                'description' => 'View authorization type permission',
                'slug' => 'authorization.type.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            6 => 
            array (
                'name' => 'authorization.type.view.any',
                'description' => 'View any authorization type permission',
                'slug' => 'authorization.type.view.any',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            7 => 
            array (
                'name' => 'authorization.type.create',
                'description' => 'Create authorization type permission',
                'slug' => 'authorization.type.create',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            8 => 
            array (
                'name' => 'authorization.type.update',
                'description' => 'Update authorization type permission',
                'slug' => 'authorization.type.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            9 => 
            array (
                'name' => 'authorization.type.delete',
                'description' => 'Delete authorization type permission',
                'slug' => 'authorization.type.delete',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            10 => 
            array (
                'name' => 'authorization.type.delete.force',
                'description' => 'Force delete authorization type permission',
                'slug' => 'authorization.type.delete.force',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            11 => 
            array (
                'name' => 'authorization.type.restore',
                'description' => 'Restore authorization type permission',
                'slug' => 'authorization.type.restore',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            12 => 
            array (
                'name' => 'authorization.permission.*',
                'description' => 'All authorization permission permissions',
                'slug' => 'authorization.permission.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            13 => 
            array (
                'name' => 'authorization.permission.view',
                'description' => 'View authorization permission permission',
                'slug' => 'authorization.permission.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            14 => 
            array (
                'name' => 'authorization.permission.view.any',
                'description' => 'View any authorization permission permission',
                'slug' => 'authorization.permission.view.any',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            15 => 
            array (
                'name' => 'authorization.permission.create',
                'description' => 'Create authorization permission permission',
                'slug' => 'authorization.permission.create',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            16 => 
            array (
                'name' => 'authorization.permission.update',
                'description' => 'Update authorization permission permission',
                'slug' => 'authorization.permission.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            17 => 
            array (
                'name' => 'authorization.permission.delete',
                'description' => 'Delete authorization permission permission',
                'slug' => 'authorization.permission.delete',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            18 => 
            array (
                'name' => 'authorization.permission.delete.force',
                'description' => 'Force delete authorization permission permission',
                'slug' => 'authorization.permission.delete.force',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            19 => 
            array (
                'name' => 'authorization.permission.restore',
                'description' => 'Restore authorization permission permission',
                'slug' => 'authorization.permission.restore',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            20 => 
            array (
                'name' => 'authorization.permission.user.*',
                'description' => 'All authorization permission relation user permissions',
                'slug' => 'authorization.permission.user.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            21 => 
            array (
                'name' => 'authorization.permission.user.view',
                'description' => 'View authorization permission relation user permission',
                'slug' => 'authorization.permission.user.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            22 => 
            array (
                'name' => 'authorization.permission.user.attach',
                'description' => 'Attach authorization permission relation user permission',
                'slug' => 'authorization.permission.user.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            23 => 
            array (
                'name' => 'authorization.permission.user.detach',
                'description' => 'Detach authorization permission relation user permission',
                'slug' => 'authorization.permission.user.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            24 => 
            array (
                'name' => 'authorization.permission.user.update',
                'description' => 'Update authorization permission relation user permission',
                'slug' => 'authorization.permission.user.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            25 => 
            array (
                'name' => 'authorization.permission.role.*',
                'description' => 'All authorization permission relation role permissions',
                'slug' => 'authorization.permission.role.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            26 => 
            array (
                'name' => 'authorization.permission.role.view',
                'description' => 'View authorization permission relation role permission',
                'slug' => 'authorization.permission.role.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            27 => 
            array (
                'name' => 'authorization.permission.role.attach',
                'description' => 'Attach authorization permission relation role permission',
                'slug' => 'authorization.permission.role.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            28 => 
            array (
                'name' => 'authorization.permission.role.detach',
                'description' => 'Detach authorization permission relation role permission',
                'slug' => 'authorization.permission.role.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            29 => 
            array (
                'name' => 'authorization.permission.role.update',
                'description' => 'Update authorization permission relation role permission',
                'slug' => 'authorization.permission.role.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            30 => 
            array (
                'name' => 'authorization.permission.team.*',
                'description' => 'All authorization permission relation team permissions',
                'slug' => 'authorization.permission.team.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            31 => 
            array (
                'name' => 'authorization.permission.team.view',
                'description' => 'View authorization permission relation team permission',
                'slug' => 'authorization.permission.team.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            32 => 
            array (
                'name' => 'authorization.permission.team.attach',
                'description' => 'Attach authorization permission relation team permission',
                'slug' => 'authorization.permission.team.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            33 => 
            array (
                'name' => 'authorization.permission.team.detach',
                'description' => 'Detach authorization permission relation team permission',
                'slug' => 'authorization.permission.team.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            34 => 
            array (
                'name' => 'authorization.permission.team.update',
                'description' => 'Update authorization permission relation team permission',
                'slug' => 'authorization.permission.team.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            35 => 
            array (
                'name' => 'authorization.permission.teammember.*',
                'description' => 'All authorization permission relation teammember permissions',
                'slug' => 'authorization.permission.teammember.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            36 => 
            array (
                'name' => 'authorization.permission.teammember.view',
                'description' => 'View authorization permission relation teammember permission',
                'slug' => 'authorization.permission.teammember.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            37 => 
            array (
                'name' => 'authorization.permission.teammember.attach',
                'description' => 'Attach authorization permission relation teammember permission',
                'slug' => 'authorization.permission.teammember.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            38 => 
            array (
                'name' => 'authorization.permission.teammember.detach',
                'description' => 'Detach authorization permission relation teammember permission',
                'slug' => 'authorization.permission.teammember.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            39 => 
            array (
                'name' => 'authorization.permission.teammember.update',
                'description' => 'Update authorization permission relation teammember permission',
                'slug' => 'authorization.permission.teammember.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            40 => 
            array (
                'name' => 'authorization.role.*',
                'description' => 'All authorization role permissions',
                'slug' => 'authorization.role.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            41 => 
            array (
                'name' => 'authorization.role.view',
                'description' => 'View authorization role permission',
                'slug' => 'authorization.role.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            42 => 
            array (
                'name' => 'authorization.role.view.any',
                'description' => 'View any authorization role permission',
                'slug' => 'authorization.role.view.any',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            43 => 
            array (
                'name' => 'authorization.role.create',
                'description' => 'Create authorization role permission',
                'slug' => 'authorization.role.create',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            44 => 
            array (
                'name' => 'authorization.role.update',
                'description' => 'Update authorization role permission',
                'slug' => 'authorization.role.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            45 => 
            array (
                'name' => 'authorization.role.delete',
                'description' => 'Delete authorization role permission',
                'slug' => 'authorization.role.delete',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            46 => 
            array (
                'name' => 'authorization.role.delete.force',
                'description' => 'Force delete authorization role permission',
                'slug' => 'authorization.role.delete.force',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            47 => 
            array (
                'name' => 'authorization.role.restore',
                'description' => 'Restore authorization role permission',
                'slug' => 'authorization.role.restore',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            48 => 
            array (
                'name' => 'authorization.role.user.*',
                'description' => 'All authorization role relation user permissions',
                'slug' => 'authorization.role.user.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            49 => 
            array (
                'name' => 'authorization.role.user.view',
                'description' => 'View authorization role relation user permission',
                'slug' => 'authorization.role.user.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            50 => 
            array (
                'name' => 'authorization.role.user.attach',
                'description' => 'Attach authorization role relation user permission',
                'slug' => 'authorization.role.user.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            51 => 
            array (
                'name' => 'authorization.role.user.detach',
                'description' => 'Detach authorization role relation user permission',
                'slug' => 'authorization.role.user.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            52 => 
            array (
                'name' => 'authorization.role.user.update',
                'description' => 'Update authorization role relation user permission',
                'slug' => 'authorization.role.user.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            53 => 
            array (
                'name' => 'authorization.role.permission.*',
                'description' => 'All authorization role relation permission permissions',
                'slug' => 'authorization.role.permission.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            54 => 
            array (
                'name' => 'authorization.role.permission.view',
                'description' => 'View authorization role relation permission permission',
                'slug' => 'authorization.role.permission.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            55 => 
            array (
                'name' => 'authorization.role.permission.attach',
                'description' => 'Attach authorization role relation permission permission',
                'slug' => 'authorization.role.permission.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            56 => 
            array (
                'name' => 'authorization.role.permission.detach',
                'description' => 'Detach authorization role relation permission permission',
                'slug' => 'authorization.role.permission.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            57 => 
            array (
                'name' => 'authorization.role.permission.update',
                'description' => 'Update authorization role relation permission permission',
                'slug' => 'authorization.role.permission.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            58 => 
            array (
                'name' => 'authorization.role.team.*',
                'description' => 'All authorization role relation team permissions',
                'slug' => 'authorization.role.team.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            59 => 
            array (
                'name' => 'authorization.role.team.view',
                'description' => 'View authorization role relation team permission',
                'slug' => 'authorization.role.team.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            60 => 
            array (
                'name' => 'authorization.role.team.attach',
                'description' => 'Attach authorization role relation team permission',
                'slug' => 'authorization.role.team.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            61 => 
            array (
                'name' => 'authorization.role.team.detach',
                'description' => 'Detach authorization role relation team permission',
                'slug' => 'authorization.role.team.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            62 => 
            array (
                'name' => 'authorization.role.team.update',
                'description' => 'Update authorization role relation team permission',
                'slug' => 'authorization.role.team.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            63 => 
            array (
                'name' => 'authorization.role.teammember.*',
                'description' => 'All authorization role relation teammember permissions',
                'slug' => 'authorization.role.teammember.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            64 => 
            array (
                'name' => 'authorization.role.teammember.view',
                'description' => 'View authorization role relation teammember permission',
                'slug' => 'authorization.role.teammember.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            65 => 
            array (
                'name' => 'authorization.role.teammember.attach',
                'description' => 'Attach authorization role relation teammember permission',
                'slug' => 'authorization.role.teammember.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            66 => 
            array (
                'name' => 'authorization.role.teammember.detach',
                'description' => 'Detach authorization role relation teammember permission',
                'slug' => 'authorization.role.teammember.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            67 => 
            array (
                'name' => 'authorization.role.teammember.update',
                'description' => 'Update authorization role relation teammember permission',
                'slug' => 'authorization.role.teammember.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            68 => 
            array (
                'name' => 'team.*',
                'description' => 'All team permissions',
                'slug' => 'team.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            69 => 
            array (
                'name' => 'team.view',
                'description' => 'View team permission',
                'slug' => 'team.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            70 => 
            array (
                'name' => 'team.view.any',
                'description' => 'View any team permission',
                'slug' => 'team.view.any',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            71 => 
            array (
                'name' => 'team.create',
                'description' => 'Create team permission',
                'slug' => 'team.create',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            72 => 
            array (
                'name' => 'team.update',
                'description' => 'Update team permission',
                'slug' => 'team.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            73 => 
            array (
                'name' => 'team.delete',
                'description' => 'Delete team permission',
                'slug' => 'team.delete',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            74 => 
            array (
                'name' => 'team.delete.force',
                'description' => 'Force delete team permission',
                'slug' => 'team.delete.force',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            75 => 
            array (
                'name' => 'team.restore',
                'description' => 'Restore team permission',
                'slug' => 'team.restore',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            76 => 
            array (
                'name' => 'team.invitation.*',
                'description' => 'All team relation invitation permissions',
                'slug' => 'team.invitation.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            77 => 
            array (
                'name' => 'team.invitation.view',
                'description' => 'View team relation invitation permission',
                'slug' => 'team.invitation.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            78 => 
            array (
                'name' => 'team.invitation.create',
                'description' => 'Create team relation invitation permission',
                'slug' => 'team.invitation.create',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            79 => 
            array (
                'name' => 'team.invitation.delete',
                'description' => 'Delete team relation invitation permission',
                'slug' => 'team.invitation.delete',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            80 => 
            array (
                'name' => 'team.invitation.update',
                'description' => 'Update team relation invitation permission',
                'slug' => 'team.invitation.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            81 => 
            array (
                'name' => 'team.member.*',
                'description' => 'All team relation member permissions',
                'slug' => 'team.member.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            82 => 
            array (
                'name' => 'team.member.view',
                'description' => 'View team relation member permission',
                'slug' => 'team.member.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            83 => 
            array (
                'name' => 'team.member.attach',
                'description' => 'Attach team relation member permission',
                'slug' => 'team.member.attach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            84 => 
            array (
                'name' => 'team.member.detach',
                'description' => 'Detach team relation member permission',
                'slug' => 'team.member.detach',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            85 => 
            array (
                'name' => 'team.member.update',
                'description' => 'Update team relation member permission',
                'slug' => 'team.member.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            86 => 
            array (
                'name' => 'user.*',
                'description' => 'All user permissions',
                'slug' => 'user.*',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            87 => 
            array (
                'name' => 'user.view',
                'description' => 'View user permission',
                'slug' => 'user.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            88 => 
            array (
                'name' => 'user.view.any',
                'description' => 'View any user permission',
                'slug' => 'user.view.any',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            89 => 
            array (
                'name' => 'user.create',
                'description' => 'Create user permission',
                'slug' => 'user.create',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            90 => 
            array (
                'name' => 'user.update',
                'description' => 'Update user permission',
                'slug' => 'user.update',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            91 => 
            array (
                'name' => 'user.delete',
                'description' => 'Delete user permission',
                'slug' => 'user.delete',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            92 => 
            array (
                'name' => 'user.delete.force',
                'description' => 'Force delete user permission',
                'slug' => 'user.delete.force',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            93 => 
            array (
                'name' => 'user.restore',
                'description' => 'Restore user permission',
                'slug' => 'user.restore',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            94 => 
            array (
                'name' => 'app.panel.view',
                'description' => 'View app panel',
                'slug' => 'app.panel.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            95 => 
            array (
                'name' => 'profile.panel.view',
                'description' => 'View profile panel',
                'slug' => 'profile.panel.view',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            96 => 
            array (
                'name' => 'team.invitation.send',
                'description' => 'Send team invitation',
                'slug' => 'team.invitation.send',
                'team_id' => NULL,
                'authorization_type_id' => 1,
                'is_active' => 1,
                'int_value' => NULL,
                'deleted_at' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ),
        ));
        
        
    }
}